### ISSUE TITLE
懒人包报错

### ISSUE THREAD

**Issue by wqshakurei** [nyaoouo/FFDraw#25]
![image](https://github.com/nyaoouo/FFDraw/assets/135227956/c580d6d8-a25d-4130-bcf2-e2b82f588c33)

**Comment by wqshakurei** [comment]
![image](https://github.com/nyaoouo/FFDraw/assets/135227956/b51aa33a-0874-404e-8e6d-d26018a9b135)

**Comment by wqshakurei** [comment]
正在启动...
[2023-06-01 19:39:40,135]       [DEBUG] [root]  current Pid:%s
[2023-06-01 19:39:40,156]       [DEBUG] [FFDraw]        set path_encoding:utf-8
[2023-06-01 19:39:40,159]       [CRITICAL]      [root]  ----------------------------------------
[2023-06-01 19:39:40,159]       [CRITICAL]      [root]  critical error occurred
[2023-06-01 19:39:40,159]       [CRITICAL]      [root]  Traceback (most recent call last):
[2023-06-01 19:39:40,159]       [CRITICAL]      [root]    File "C:\Users\ASUS\DOWNLO~1\FFD\FFDraw\main.py", line 24, in main
[2023-06-01 19:39:40,159]       [CRITICAL]      [root]      instance = FFDraw(next(pid_by_executable(b'ffxiv_dx11.exe')))
[2023-06-01 19:39:40,159]       [CRITICAL]      [root]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-06-01 19:39:40,159]       [CRITICAL]      [root]    File "C:\Users\ASUS\DOWNLO~1\FFD\FFDraw\ff_draw\main.py", line 68, in __init__
[2023-06-01 19:39:40,159]       [CRITICAL]      [root]      self.mem = mem.XivMem(self, pid)
[2023-06-01 19:39:40,159]       [CRITICAL]      [root]                 ^^^^^^^^^^^^^^^^^^^^^
[2023-06-01 19:39:40,159]       [CRITICAL]      [root]    File "C:\Users\ASUS\DOWNLO~1\FFD\FFDraw\ff_draw\mem\__init__.py", line 160, in __init__
[2023-06-01 19:39:40,159]       [CRITICAL]      [root]      self.base_module = ny_proc.get_base_module(self.handle)
[2023-06-01 19:39:40,159]       [CRITICAL]      [root]                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-06-01 19:39:40,159]       [CRITICAL]      [root]    File "C:\Users\ASUS\DOWNLO~1\FFD\FFDraw\nylib\utils\win32\process.py", line 55, in get_base_module
[2023-06-01 19:39:40,159]       [CRITICAL]      [root]      return next(iter(enum_process_module(handle)))
[2023-06-01 19:39:40,159]       [CRITICAL]      [root]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-06-01 19:39:40,159]       [CRITICAL]      [root]    File "C:\Users\ASUS\DOWNLO~1\FFD\FFDraw\nylib\utils\win32\process.py", line 41, in enum_process_module
[2023-06-01 19:39:40,159]       [CRITICAL]      [root]      raise exception.WinAPIError(error_code)
[2023-06-01 19:39:40,159]       [CRITICAL]      [root]  nylib.utils.win32.exception.WinAPIError: Windows api error, error_code: 0X12B
[2023-06-01 19:39:40,159]       [CRITICAL]      [root]  ----------------------------------------
[2023-06-01 19:39:40,161]       [DEBUG] [urllib3.connectionpool]        Starting new HTTPS connection (1): raw.githubusercontent.com:443
Press any key to continue . . . [2023-06-01 19:39:40,908]       [DEBUG] [urllib3.connectionpool]        https://raw.githubusercontent.com:443 "GET /nyaoouo/FFDraw/master/version.txt HTTP/1.1" 200 27
[2023-06-01 19:39:40,908]       [INFO]  [UpdateChecker] local version: (0, 15, 1)    remote version: (0, 15, 1)

**Comment by wqshakurei** [comment]
![image](https://github.com/nyaoouo/FFDraw/assets/135227956/9ff138a4-06df-42e8-b4c1-edca30fb07d1)

**Comment by wqshakurei** [comment]
![image](https://github.com/nyaoouo/FFDraw/assets/135227956/98679f7c-f15f-4d65-ae2e-1b52d2f3ed76)
这是exe的报错，上面的是run.bat的报错

**Comment by nyaoouo** [comment]
注意管理员权限，尝试重启，另外请先尝试阅读报错，连不上github，懒人包启动出问题请先前往对应repo进行询问
