### ISSUE TITLE
疑似nylib里的东西出错

### ISSUE THREAD

**Issue by Cyf5119** [nyaoouo/FFDraw#36]
疑似nylib里的东西出错，今天更新之后，不论是小白懒人包版本还是python版本都是这个同样的错误

pip环境包更新完成

正在启动...
[2023-06-24 23:44:38,707]       [DEBUG] [root]  current Pid:14232 game Pid:9000
[2023-06-24 23:44:38,709]       [DEBUG] [FFDraw]        set path_encoding:gbk
[2023-06-24 23:44:38,714]       [DEBUG] [urllib3.connectionpool]        Starting new HTTPS connection (1): raw.fastgit.org:443
[2023-06-24 23:44:39,183]       [CRITICAL]      [root]  ----------------------------------------
[2023-06-24 23:44:39,183]       [CRITICAL]      [root]  critical error occurred
[2023-06-24 23:44:39,183]       [CRITICAL]      [root]  Traceback (most recent call last):
[2023-06-24 23:44:39,183]       [CRITICAL]      [root]    File "D:\Games\FFXIV\FFD\FFDraw\main.py", line 49, in main
[2023-06-24 23:44:39,183]       [CRITICAL]      [root]      instance = FFDraw(game_pid)
[2023-06-24 23:44:39,183]       [CRITICAL]      [root]                 ^^^^^^^^^^^^^^^^
[2023-06-24 23:44:39,183]       [CRITICAL]      [root]    File "D:\Games\FFXIV\FFD\FFDraw\ff_draw\main.py", line 67, in __init__
[2023-06-24 23:44:39,183]       [CRITICAL]      [root]      self.mem = mem.XivMem(self, pid)
[2023-06-24 23:44:39,183]       [CRITICAL]      [root]                 ^^^^^^^^^^^^^^^^^^^^^
[2023-06-24 23:44:39,183]       [CRITICAL]      [root]    File "D:\Games\FFXIV\FFD\FFDraw\ff_draw\mem\__init__.py", line 194, in __init__
[2023-06-24 23:44:39,183]       [CRITICAL]      [root]      self.add_game_main_func, self.remove_game_main_func, self.call_once_game_main = hook_main_update.install(self)
[2023-06-24 23:44:39,183]       [CRITICAL]      [root]                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-06-24 23:44:39,183]       [CRITICAL]      [root]    File "D:\Games\FFXIV\FFD\FFDraw\ff_draw\mem\hook_main_update.py", line 72, in install
[2023-06-24 23:44:39,183]       [CRITICAL]      [root]      install_cnt = mem.inject_handle.run(f'on_game_update_addr = {on_game_update_addr}' + payload)
[2023-06-24 23:44:39,183]       [CRITICAL]      [root]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-06-24 23:44:39,183]       [CRITICAL]      [root]    File "D:\Games\FFXIV\FFD\FFDraw\NyLib\nylib\utils\win32\inject_rpc.py", line 122, in run
[2023-06-24 23:44:39,183]       [CRITICAL]      [root]      return self.client.rpc.run(code, args, res_key)
[2023-06-24 23:44:39,183]       [CRITICAL]      [root]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-06-24 23:44:39,183]       [CRITICAL]      [root]    File "D:\Games\FFXIV\FFD\FFDraw\NyLib\nylib\rpc\namedpipe_pickle.py", line 138, in func
[2023-06-24 23:44:39,183]       [CRITICAL]      [root]      return self.remote_call(item, _args, _kwargs)
[2023-06-24 23:44:39,183]       [CRITICAL]      [root]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-06-24 23:44:39,183]       [CRITICAL]      [root]    File "D:\Games\FFXIV\FFD\FFDraw\NyLib\nylib\rpc\namedpipe_pickle.py", line 222, in remote_call
[2023-06-24 23:44:39,183]       [CRITICAL]      [root]      raise set_exc(*res)
[2023-06-24 23:44:39,183]       [CRITICAL]      [root]  TypeError: run_rpc_server_main.<locals>.run_call() takes from 1 to 2 positional arguments but 3 were given
[2023-06-24 23:44:39,183]       [CRITICAL]      [root]  ----------------------------------------
Press any key to continue . . . [2023-06-24 23:44:39,845]       [DEBUG] [urllib3.connectionpool]        https://raw.fastgit.org:443 "GET /nyaoouo/FFDraw/master/version.txt HTTP/1.1" 200 27
[2023-06-24 23:44:39,846]       [INFO]  [UpdateChecker] local version: (0, 16, 0)    remote version: (0, 16, 0)

**Comment by nyaoouo** [comment]
https://git-scm.com/book/zh/v2/Git-%E5%B7%A5%E5%85%B7-%E5%AD%90%E6%A8%A1%E5%9D%97
