### ISSUE TITLE
Nylib更新后无法启动FFDraw

### ISSUE THREAD

**Issue by GodofTheFallen** [nyaoouo/FFDraw#43]
报错信息
```
[2023-09-16 22:47:40,700]       [DEBUG] [root]  current Pid:33140 game Pid:31368
[2023-09-16 22:47:40,702]       [DEBUG] [FFDraw]        set http proxy: http://127.0.0.1:7890
[2023-09-16 22:47:40,702]       [DEBUG] [FFDraw]        set https proxy: http://127.0.0.1:7890
[2023-09-16 22:47:40,702]       [DEBUG] [FFDraw]        set path_encoding:utf-8
[2023-09-16 22:47:40,706]       [DEBUG] [urllib3.connectionpool]        Starting new HTTPS connection (1): raw.githubusercontent.com:443
[2023-09-16 22:47:41,135]       [CRITICAL]      [root]  ----------------------------------------
[2023-09-16 22:47:41,135]       [CRITICAL]      [root]  critical error occurred
[2023-09-16 22:47:41,135]       [CRITICAL]      [root]  Traceback (most recent call last):
[2023-09-16 22:47:41,135]       [CRITICAL]      [root]    File "C:\Game\FFDraw\main.py", line 49, in main
[2023-09-16 22:47:41,135]       [CRITICAL]      [root]      instance = FFDraw(game_pid)
[2023-09-16 22:47:41,135]       [CRITICAL]      [root]                 ^^^^^^^^^^^^^^^^
[2023-09-16 22:47:41,135]       [CRITICAL]      [root]    File "C:\Game\FFDraw\ff_draw\main.py", line 70, in __init__
[2023-09-16 22:47:41,135]       [CRITICAL]      [root]      self.mem = mem.XivMem(self, pid)
[2023-09-16 22:47:41,135]       [CRITICAL]      [root]                 ^^^^^^^^^^^^^^^^^^^^^
[2023-09-16 22:47:41,135]       [CRITICAL]      [root]    File "C:\Game\FFDraw\ff_draw\mem\__init__.py", line 147, in __init__
[2023-09-16 22:47:41,135]       [CRITICAL]      [root]      self.add_game_main_func, self.remove_game_main_func, self.call_once_game_main = hook_main_update.install(self)
[2023-09-16 22:47:41,135]       [CRITICAL]      [root]                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-09-16 22:47:41,135]       [CRITICAL]      [root]    File "C:\Game\FFDraw\ff_draw\mem\hook_main_update.py", line 69, in install
[2023-09-16 22:47:41,135]       [CRITICAL]      [root]      install_cnt = mem.inject_handle.run(f'on_game_update_addr = {on_game_update_addr}' + payload)
[2023-09-16 22:47:41,135]       [CRITICAL]      [root]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-09-16 22:47:41,135]       [CRITICAL]      [root]    File "C:\Game\FFDraw\NyLib\nylib\utils\win32\inject_rpc.py", line 118, in run
[2023-09-16 22:47:41,135]       [CRITICAL]      [root]      return self.client.rpc.run(code, args, res_key, filename)
[2023-09-16 22:47:41,135]       [CRITICAL]      [root]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-09-16 22:47:41,135]       [CRITICAL]      [root]    File "C:\Game\FFDraw\NyLib\nylib\rpc\namedpipe_pickle.py", line 138, in func
[2023-09-16 22:47:41,135]       [CRITICAL]      [root]      return self.remote_call(item, _args, _kwargs)
[2023-09-16 22:47:41,135]       [CRITICAL]      [root]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-09-16 22:47:41,135]       [CRITICAL]      [root]    File "C:\Game\FFDraw\NyLib\nylib\rpc\namedpipe_pickle.py", line 222, in remote_call
[2023-09-16 22:47:41,135]       [CRITICAL]      [root]      raise set_exc(*res)
[2023-09-16 22:47:41,135]       [CRITICAL]      [root]  TypeError: run_rpc_server_main.<locals>.run_call() takes from 2 to 3 positional arguments but 4 were given
[2023-09-16 22:47:41,135]       [CRITICAL]      [root]  ----------------------------------------
请按任意键继续. . . [2023-09-16 22:47:41,459]   [DEBUG] [urllib3.connectionpool]        https://raw.githubusercontent.com:443 "GET /nyaoouo/FFDraw/master/version.txt HTTP/1.1" 200 26
[2023-09-16 22:47:41,460]       [INFO]  [UpdateChecker] local version: (1, 0, 0)    remote version: (1, 0, 0)
```

**Comment by nyaoouo** [comment]
`git submodule update --remote`

**Comment by GodofTheFallen** [comment]
Update过了，仍然有这样的报错

**Comment by GodofTheFallen** [comment]
```
[2023-09-17 00:14:47,750]       [DEBUG] [root]  current Pid:32772 game Pid:31368
[2023-09-17 00:14:47,752]       [DEBUG] [FFDraw]        set http proxy: http://127.0.0.1:7890
[2023-09-17 00:14:47,752]       [DEBUG] [FFDraw]        set https proxy: http://127.0.0.1:7890
[2023-09-17 00:14:47,752]       [DEBUG] [FFDraw]        set path_encoding:utf-8
[2023-09-17 00:14:47,755]       [DEBUG] [urllib3.connectionpool]        Starting new HTTPS connection (1): raw.githubusercontent.com:443
[2023-09-17 00:14:48,260]       [CRITICAL]      [root]  ----------------------------------------
[2023-09-17 00:14:48,260]       [CRITICAL]      [root]  critical error occurred
[2023-09-17 00:14:48,260]       [CRITICAL]      [root]  Traceback (most recent call last):
[2023-09-17 00:14:48,260]       [CRITICAL]      [root]    File "C:\Game\FFDraw\main.py", line 49, in main
[2023-09-17 00:14:48,260]       [CRITICAL]      [root]      instance = FFDraw(game_pid)
[2023-09-17 00:14:48,260]       [CRITICAL]      [root]                 ^^^^^^^^^^^^^^^^
[2023-09-17 00:14:48,260]       [CRITICAL]      [root]    File "C:\Game\FFDraw\ff_draw\main.py", line 70, in __init__
[2023-09-17 00:14:48,260]       [CRITICAL]      [root]      self.mem = mem.XivMem(self, pid)
[2023-09-17 00:14:48,260]       [CRITICAL]      [root]                 ^^^^^^^^^^^^^^^^^^^^^
[2023-09-17 00:14:48,260]       [CRITICAL]      [root]    File "C:\Game\FFDraw\ff_draw\mem\__init__.py", line 147, in __init__
[2023-09-17 00:14:48,260]       [CRITICAL]      [root]      self.add_game_main_func, self.remove_game_main_func, self.call_once_game_main = hook_main_update.install(self)
[2023-09-17 00:14:48,260]       [CRITICAL]      [root]                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-09-17 00:14:48,260]       [CRITICAL]      [root]    File "C:\Game\FFDraw\ff_draw\mem\hook_main_update.py", line 69, in install
[2023-09-17 00:14:48,260]       [CRITICAL]      [root]      install_cnt = mem.inject_handle.run(f'on_game_update_addr = {on_game_update_addr}' + payload)
[2023-09-17 00:14:48,260]       [CRITICAL]      [root]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-09-17 00:14:48,260]       [CRITICAL]      [root]    File "C:\Game\FFDraw\NyLib\nylib\utils\win32\inject_rpc.py", line 118, in run
[2023-09-17 00:14:48,260]       [CRITICAL]      [root]      return self.client.rpc.run(code, args, res_key, filename)
[2023-09-17 00:14:48,260]       [CRITICAL]      [root]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-09-17 00:14:48,260]       [CRITICAL]      [root]    File "C:\Game\FFDraw\NyLib\nylib\rpc\namedpipe_pickle.py", line 138, in func
[2023-09-17 00:14:48,260]       [CRITICAL]      [root]      return self.remote_call(item, _args, _kwargs)
[2023-09-17 00:14:48,260]       [CRITICAL]      [root]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-09-17 00:14:48,260]       [CRITICAL]      [root]    File "C:\Game\FFDraw\NyLib\nylib\rpc\namedpipe_pickle.py", line 222, in remote_call
[2023-09-17 00:14:48,260]       [CRITICAL]      [root]      raise set_exc(*res)
[2023-09-17 00:14:48,260]       [CRITICAL]      [root]  TypeError: run_rpc_server_main.<locals>.run_call() takes from 2 to 3 positional arguments but 4 were given
[2023-09-17 00:14:48,260]       [CRITICAL]      [root]  ----------------------------------------
请按任意键继续. . . [2023-09-17 00:14:49,035]   [DEBUG] [urllib3.connectionpool]        https://raw.githubusercontent.com:443 "GET /nyaoouo/FFDraw/master/version.txt HTTP/1.1" 200 26
[2023-09-17 00:14:49,035]       [INFO]  [UpdateChecker] local version: (1, 0, 0)    remote version: (1, 0, 0)
```
